using System.Text.Json;
using Zephyrus.Core.Agents;
using Zephyrus.Core.Enums;
using Zephyrus.Core.Interfaces;

namespace Zephyrus.Infrastructure.AI.Agents;

/// <summary>
/// Task Agent — breaks down an approved ADR into discrete, assignable tasks.
/// Each task maps to a GitHub Issue and is tagged with the responsible agent type.
/// </summary>
public sealed class TaskAgent : IAgent<TaskAgentInput, TaskAgentOutput>
{
    private readonly ILanguageModel _languageModel;

    private const string SystemPrompt = @"You are the Task Agent for Zephyrus, an AI-powered software delivery platform.

Your job is to break down an approved Architecture Decision Record (ADR) into discrete, implementable tasks.
Each task will become a GitHub Issue and be assigned to a specialized Code Agent.

## Output Format

You MUST output ONLY valid JSON (no markdown fences, no commentary) with this exact structure:

{
  ""tasks"": [
    {
      ""title"": ""Short, actionable task title"",
      ""body"": ""Detailed description in Markdown with acceptance criteria"",
      ""agent_type"": ""BE""
    }
  ]
}

## Agent Types

Assign each task to exactly one agent type:
- **BE** — Backend (.NET/C#): API endpoints, services, business logic, EF Core repositories.
- **FE** — Frontend (Next.js/TypeScript): Pages, components, API client calls, styling.
- **DB** — Database: EF Core migrations, schema changes, seed data.
- **DevOps** — DevOps: CI/CD, GitHub Actions, Docker, deployment config.

## Rules

- Each task must be small enough to implement in a single pull request.
- Task titles must be specific and start with a verb (Add, Create, Implement, Update, Configure).
- Task bodies must include acceptance criteria as a checkbox list.
- Order tasks by dependency — tasks that others depend on come first.
- Database tasks come before backend tasks that depend on new tables.
- Backend tasks come before frontend tasks that consume new endpoints.
- Include both happy-path implementation and basic error handling in each task.
- Do not create testing tasks — tests are handled by the QA Agent later.
- Do not create documentation tasks — docs are generated by other agents.
- Output ONLY the JSON. No preamble, no markdown fences, no commentary.";

    public TaskAgent(ILanguageModel languageModel)
    {
        _languageModel = languageModel;
    }

    public async Task<TaskAgentOutput> RunAsync(TaskAgentInput input, CancellationToken ct = default)
    {
        var userMessage = $"""
            ## Approved PRD
            {input.ApprovedPrd}

            ## Approved ADR
            {input.ApprovedAdr}

            ## Project Constitution
            {input.ProjectConstitution}
            """;

        var json = await _languageModel.GenerateAsync(SystemPrompt, userMessage, ct);

        var tasks = ParseTasks(json);

        var repoPath = $"docs/tasks-{input.FeatureSlug}.md";

        // Build a human-readable markdown summary of the task breakdown
        var markdown = BuildMarkdown(input.FeatureSlug, tasks);

        return new TaskAgentOutput
        {
            Markdown = markdown,
            RepositoryPath = repoPath,
            Tasks = tasks
        };
    }

    private static List<TaskDefinition> ParseTasks(string json)
    {
        // Strip markdown code fences if the LLM wraps the output
        json = json.Trim();
        if (json.StartsWith("```"))
        {
            var firstNewline = json.IndexOf('\n');
            if (firstNewline >= 0)
                json = json[(firstNewline + 1)..];
            if (json.EndsWith("```"))
                json = json[..^3];
            json = json.Trim();
        }

        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;
        var tasksArray = root.GetProperty("tasks");

        var tasks = new List<TaskDefinition>();

        foreach (var taskElement in tasksArray.EnumerateArray())
        {
            var title = taskElement.GetProperty("title").GetString()
                ?? throw new InvalidOperationException("Task title is required.");
            var body = taskElement.GetProperty("body").GetString()
                ?? throw new InvalidOperationException("Task body is required.");
            var agentTypeStr = taskElement.GetProperty("agent_type").GetString()
                ?? throw new InvalidOperationException("Task agent_type is required.");

            if (!Enum.TryParse<AgentType>(agentTypeStr, ignoreCase: true, out var agentType))
            {
                throw new InvalidOperationException(
                    $"Invalid agent_type '{agentTypeStr}'. Must be one of: BE, FE, DB, DevOps.");
            }

            tasks.Add(new TaskDefinition
            {
                Title = title,
                Body = body,
                AgentType = agentType
            });
        }

        return tasks;
    }

    private static string BuildMarkdown(string featureSlug, IReadOnlyList<TaskDefinition> tasks)
    {
        var lines = new List<string>
        {
            $"# Task Breakdown: {featureSlug}",
            "",
            $"Total tasks: {tasks.Count}",
            ""
        };

        for (var i = 0; i < tasks.Count; i++)
        {
            var task = tasks[i];
            lines.Add($"## Task {i + 1}: {task.Title}");
            lines.Add($"**Agent:** {task.AgentType}");
            lines.Add("");
            lines.Add(task.Body);
            lines.Add("");
        }

        return string.Join("\n", lines);
    }
}
