namespace Zephyrus.Core.Agents;

/// <summary>
/// Output from the Code Agent. The Action field determines whether the agent
/// is requesting more files to read or generating final code.
/// </summary>
public sealed class CodeAgentOutput
{
    public required string Action { get; init; }
    public IReadOnlyList<GeneratedFile> Files { get; init; } = [];
    public IReadOnlyList<string> RequestedFiles { get; init; } = [];
    public string? Reasoning { get; init; }
    public required string SystemPrompt { get; init; }
    public required string UserMessage { get; init; }
    public required string RawResponse { get; init; }
}

/// <summary>
/// A single file generated by the Code Agent.
/// </summary>
public sealed class GeneratedFile
{
    public required string Path { get; init; }
    public required string Content { get; init; }
}
