namespace Zephyrus.Core.Agents;

/// <summary>
/// Output from the Code Agent: a list of files to commit to the feature branch.
/// </summary>
public sealed class CodeAgentOutput
{
    public required IReadOnlyList<GeneratedFile> Files { get; init; }
}

/// <summary>
/// A single file generated by the Code Agent.
/// </summary>
public sealed class GeneratedFile
{
    public required string Path { get; init; }
    public required string Content { get; init; }
}
