// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Zephyrus.Infrastructure.Persistence;

#nullable enable

namespace Zephyrus.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ZephyrusDbContext))]
partial class ZephyrusDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Zephyrus.Core.Entities.Project", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<string>("Name").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("name");
            b.Property<string>("Description").IsRequired().HasColumnType("text").HasColumnName("description");
            b.Property<string>("Config").IsRequired().HasColumnType("jsonb").HasColumnName("config");
            b.Property<string>("RepositorySlug").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("repository_slug");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
            b.HasKey("Id");
            b.ToTable("projects", (string)null);
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Feature", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("ProjectId").HasColumnType("uuid").HasColumnName("project_id");
            b.Property<string>("Prompt").IsRequired().HasColumnType("text").HasColumnName("prompt");
            b.Property<string>("Status").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("status");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
            b.HasKey("Id");
            b.HasIndex("ProjectId").HasDatabaseName("IX_features_project_id");
            b.ToTable("features", (string)null);
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Artifact", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("FeatureId").HasColumnType("uuid").HasColumnName("feature_id");
            b.Property<string>("Type").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("type");
            b.Property<string>("RepositoryPath").IsRequired().HasMaxLength(1024).HasColumnType("character varying(1024)").HasColumnName("repository_path");
            b.Property<string>("ApprovedBy").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("approved_by");
            b.Property<DateTime?>("ApprovedAt").HasColumnType("timestamp with time zone").HasColumnName("approved_at");
            b.HasKey("Id");
            b.HasIndex("FeatureId").HasDatabaseName("IX_artifacts_feature_id");
            b.ToTable("artifacts", (string)null);
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.TaskItem", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("FeatureId").HasColumnType("uuid").HasColumnName("feature_id");
            b.Property<int?>("ExternalIssueId").HasColumnType("integer").HasColumnName("external_issue_id");
            b.Property<string>("Title").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("title");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("status");
            b.Property<int?>("PrId").HasColumnType("integer").HasColumnName("pr_id");
            b.Property<string>("AgentType").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)").HasColumnName("agent_type");
            b.HasKey("Id");
            b.HasIndex("FeatureId").HasDatabaseName("IX_task_items_feature_id");
            b.ToTable("task_items", (string)null);
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.PipelineEvent", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("FeatureId").HasColumnType("uuid").HasColumnName("feature_id");
            b.Property<string>("FromStatus").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("from_status");
            b.Property<string>("ToStatus").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("to_status");
            b.Property<string>("TriggeredBy").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("triggered_by");
            b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone").HasColumnName("timestamp");
            b.HasKey("Id");
            b.HasIndex("FeatureId").HasDatabaseName("IX_pipeline_events_feature_id");
            b.ToTable("pipeline_events", (string)null);
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Deployment", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("FeatureId").HasColumnType("uuid").HasColumnName("feature_id");
            b.Property<string>("Sha").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("sha");
            b.Property<string>("Environment").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("environment");
            b.Property<DateTime>("DeployedAt").HasColumnType("timestamp with time zone").HasColumnName("deployed_at");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("status");
            b.HasKey("Id");
            b.HasIndex("FeatureId").HasDatabaseName("IX_deployments_feature_id");
            b.ToTable("deployments", (string)null);
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Feature", b =>
        {
            b.HasOne("Zephyrus.Core.Entities.Project", "Project")
                .WithMany("Features")
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Project");
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Artifact", b =>
        {
            b.HasOne("Zephyrus.Core.Entities.Feature", "Feature")
                .WithMany("Artifacts")
                .HasForeignKey("FeatureId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Feature");
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.TaskItem", b =>
        {
            b.HasOne("Zephyrus.Core.Entities.Feature", "Feature")
                .WithMany("Tasks")
                .HasForeignKey("FeatureId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Feature");
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.PipelineEvent", b =>
        {
            b.HasOne("Zephyrus.Core.Entities.Feature", "Feature")
                .WithMany("PipelineEvents")
                .HasForeignKey("FeatureId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Feature");
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Deployment", b =>
        {
            b.HasOne("Zephyrus.Core.Entities.Feature", "Feature")
                .WithMany("Deployments")
                .HasForeignKey("FeatureId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Feature");
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Project", b =>
        {
            b.Navigation("Features");
        });

        modelBuilder.Entity("Zephyrus.Core.Entities.Feature", b =>
        {
            b.Navigation("Artifacts");
            b.Navigation("Tasks");
            b.Navigation("PipelineEvents");
            b.Navigation("Deployments");
        });
#pragma warning restore 612, 618
    }
}
