using Zephyrus.Core.Interfaces;

namespace Zephyrus.IntegrationTests.Fakes;

/// <summary>
/// Fake language model that returns canned markdown responses.
/// Inspects the system prompt to determine which agent is calling.
/// </summary>
public sealed class FakeLanguageModel : ILanguageModel
{
    public List<(string SystemPrompt, string UserMessage)> Calls { get; } = new();

    public Task<string> GenerateAsync(string systemPrompt, string userMessage, CancellationToken ct = default)
    {
        Calls.Add((systemPrompt, userMessage));

        // Return different canned responses based on agent type
        if (systemPrompt.Contains("PRD Agent"))
        {
            return Task.FromResult("""
                # PRD: Test Feature

                ## Problem Statement
                This is a test PRD generated by the fake language model.

                ## Target Users
                Developers testing the pipeline.

                ## Goals
                - Validate the pipeline flow end-to-end.

                ## Non-Goals
                - Production readiness.

                ## User Stories

                ### Story 1: Pipeline Test
                - **Given** a feature in Ideation status
                - **When** the PRD agent is invoked
                - **Then** a PRD artifact is generated

                ## Acceptance Criteria
                - [ ] PRD is committed to the repository.
                - [ ] Feature advances to PrdPending status.

                ## Open Questions
                - None for testing.
                """);
        }

        if (systemPrompt.Contains("Architect Agent"))
        {
            return Task.FromResult("""
                # ADR: Test Feature

                ## Summary
                Architecture decision record for the test feature.

                ## New Components
                - TestService in Application layer.

                ## Database Changes
                - No changes needed for test.

                ## API Contracts
                ### `POST /api/test`
                - **Request:** `{ "data": "string" }`
                - **Response:** `{ "id": "uuid" }`
                - **Status codes:** 200, 400

                ## External Dependencies
                - None.

                ## Sequence Diagram
                1. Client sends request.
                2. API validates input.
                3. Service processes data.
                4. Response returned.

                ## Estimated Complexity
                | Area | Estimate | Notes |
                |------|----------|-------|
                | Backend | S | Simple CRUD |
                | Frontend | S | Single form |
                | Database | S | One table |

                ## Risks & Open Questions
                - None for testing.
                """);
        }

        if (systemPrompt.Contains("QA Agent"))
        {
            return Task.FromResult("""
                {
                  "test_files": [
                    {
                      "path": "tests/ExampleTests.cs",
                      "content": "using Xunit;\n\npublic class ExampleTests\n{\n    [Fact]\n    public void Example_WhenCalled_ShouldReturnTrue()\n    {\n        Assert.True(true);\n    }\n}"
                    }
                  ],
                  "report": "# QA Report\n\n## Summary\nAll tests passed.\n\n## Test Coverage\n- ExampleTests: 1 test\n\n## Results\n- Passed: 1\n- Failed: 0\n- Coverage: 80%"
                }
                """);
        }

        if (systemPrompt.Contains("Code Agent"))
        {
            return Task.FromResult("""
                {
                  "files": [
                    {
                      "path": "src/Example.cs",
                      "content": "namespace Example;\n\npublic class Example\n{\n    public string Name { get; set; } = string.Empty;\n}"
                    }
                  ]
                }
                """);
        }

        if (systemPrompt.Contains("Task Agent"))
        {
            return Task.FromResult("""
                {
                  "tasks": [
                    {
                      "title": "Create database migration for test table",
                      "body": "## Description\nAdd EF Core migration for the test table.\n\n## Acceptance Criteria\n- [ ] Migration creates test table\n- [ ] Migration is reversible",
                      "agent_type": "DB"
                    },
                    {
                      "title": "Implement TestService in Application layer",
                      "body": "## Description\nAdd the TestService that processes test data.\n\n## Acceptance Criteria\n- [ ] Service validates input\n- [ ] Service returns correct response",
                      "agent_type": "BE"
                    },
                    {
                      "title": "Add test page to frontend",
                      "body": "## Description\nCreate the Next.js page for the test feature.\n\n## Acceptance Criteria\n- [ ] Page renders form\n- [ ] Page calls API endpoint",
                      "agent_type": "FE"
                    }
                  ]
                }
                """);
        }

        return Task.FromResult("# Fake agent output");
    }
}
